# Setup
title:               Ina Tang
tagline:             ''
description:         "Welcome to my very first website : D"
url:                 https://i7t5.github.io
baseurl:             ''
paginate:            5
permalink:           pretty

# About/contact
author:
  name:              Ina Tang
  url:               https://github.com/I7T5
  email:             inatang75@outlook.com

# Gems
plugins:
  - jekyll-paginate
  - jekyll-github-metadata

# Custom vars
version:             0.0.1
google_analytics_id: #UA-XXXX-Y
